version: 1
builder:
  configs:
    - documentation_targets:
        - WasmKit
        - WasmKitWASI
        - WasmParser
        - WasmTypes
        - WASI
        - WAT
        - WIT
        - WITExtractor
        - WITOverlayGenerator
        - WITTool
