;; GENERATED FILE, DO NOT EDIT. Regenerate with:
;;   python3 Tests/WasmKitTests/ExtraSuite/accumulator_copy.gen.py > Tests/WasmKitTests/ExtraSuite/accumulator_copy.wast

(module
  (memory 1)
  (data (i32.const 0) "\00\00\00\00\01\00\00\00\ff\ff\ff\ff\05\00\00\00\ff\ff\ff\7f\00\00\00\80\78\56\34\12")
  (global $g (mut i32) (i32.const 0))
  (func $add.swap.set (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.add (local.get $a) (local.get $b)) (local.set $a (local.get $b)) (local.set $b) (i32.const 0) (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $add.swap.set.ref (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.add (local.get $a) (local.get $b)) (local.set $a (local.get $b)) (drop (global.get $g)) (local.set $b) (i32.const 0) (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $add.swap.tee (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.add (local.get $a) (local.get $b)) (local.set $a (local.get $b)) (local.tee $b)  (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $add.swap.tee.ref (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.add (local.get $a) (local.get $b)) (local.set $a (local.get $b)) (drop (global.get $g)) (local.tee $b)  (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $add.unrelated.set (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.add (local.get $a) (local.get $b)) (local.set $c (local.get $a)) (local.set $b) (i32.const 0) (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $add.unrelated.set.ref (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.add (local.get $a) (local.get $b)) (local.set $c (local.get $a)) (drop (global.get $g)) (local.set $b) (i32.const 0) (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $add.unrelated.tee (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.add (local.get $a) (local.get $b)) (local.set $c (local.get $a)) (local.tee $b)  (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $add.unrelated.tee.ref (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.add (local.get $a) (local.get $b)) (local.set $c (local.get $a)) (drop (global.get $g)) (local.tee $b)  (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $add.same_dest.set (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.add (local.get $a) (local.get $b)) (local.set $a (local.get $b)) (local.set $a) (i32.const 0) (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $add.same_dest.set.ref (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.add (local.get $a) (local.get $b)) (local.set $a (local.get $b)) (drop (global.get $g)) (local.set $a) (i32.const 0) (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $add.same_dest.tee (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.add (local.get $a) (local.get $b)) (local.set $a (local.get $b)) (local.tee $a)  (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $add.same_dest.tee.ref (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.add (local.get $a) (local.get $b)) (local.set $a (local.get $b)) (drop (global.get $g)) (local.tee $a)  (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $add.from_dest.set (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.add (local.get $a) (local.get $b)) (local.set $c (local.get $b)) (local.set $b) (i32.const 0) (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $add.from_dest.set.ref (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.add (local.get $a) (local.get $b)) (local.set $c (local.get $b)) (drop (global.get $g)) (local.set $b) (i32.const 0) (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $add.from_dest.tee (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.add (local.get $a) (local.get $b)) (local.set $c (local.get $b)) (local.tee $b)  (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $add.from_dest.tee.ref (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.add (local.get $a) (local.get $b)) (local.set $c (local.get $b)) (drop (global.get $g)) (local.tee $b)  (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $sub.swap.set (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.sub (local.get $a) (local.get $b)) (local.set $a (local.get $b)) (local.set $b) (i32.const 0) (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $sub.swap.set.ref (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.sub (local.get $a) (local.get $b)) (local.set $a (local.get $b)) (drop (global.get $g)) (local.set $b) (i32.const 0) (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $sub.swap.tee (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.sub (local.get $a) (local.get $b)) (local.set $a (local.get $b)) (local.tee $b)  (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $sub.swap.tee.ref (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.sub (local.get $a) (local.get $b)) (local.set $a (local.get $b)) (drop (global.get $g)) (local.tee $b)  (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $sub.unrelated.set (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.sub (local.get $a) (local.get $b)) (local.set $c (local.get $a)) (local.set $b) (i32.const 0) (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $sub.unrelated.set.ref (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.sub (local.get $a) (local.get $b)) (local.set $c (local.get $a)) (drop (global.get $g)) (local.set $b) (i32.const 0) (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $sub.unrelated.tee (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.sub (local.get $a) (local.get $b)) (local.set $c (local.get $a)) (local.tee $b)  (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $sub.unrelated.tee.ref (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.sub (local.get $a) (local.get $b)) (local.set $c (local.get $a)) (drop (global.get $g)) (local.tee $b)  (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $sub.same_dest.set (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.sub (local.get $a) (local.get $b)) (local.set $a (local.get $b)) (local.set $a) (i32.const 0) (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $sub.same_dest.set.ref (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.sub (local.get $a) (local.get $b)) (local.set $a (local.get $b)) (drop (global.get $g)) (local.set $a) (i32.const 0) (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $sub.same_dest.tee (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.sub (local.get $a) (local.get $b)) (local.set $a (local.get $b)) (local.tee $a)  (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $sub.same_dest.tee.ref (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.sub (local.get $a) (local.get $b)) (local.set $a (local.get $b)) (drop (global.get $g)) (local.tee $a)  (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $sub.from_dest.set (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.sub (local.get $a) (local.get $b)) (local.set $c (local.get $b)) (local.set $b) (i32.const 0) (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $sub.from_dest.set.ref (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.sub (local.get $a) (local.get $b)) (local.set $c (local.get $b)) (drop (global.get $g)) (local.set $b) (i32.const 0) (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $sub.from_dest.tee (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.sub (local.get $a) (local.get $b)) (local.set $c (local.get $b)) (local.tee $b)  (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $sub.from_dest.tee.ref (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.sub (local.get $a) (local.get $b)) (local.set $c (local.get $b)) (drop (global.get $g)) (local.tee $b)  (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $rotl.swap.set (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.rotl (local.get $a) (local.get $b)) (local.set $a (local.get $b)) (local.set $b) (i32.const 0) (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $rotl.swap.set.ref (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.rotl (local.get $a) (local.get $b)) (local.set $a (local.get $b)) (drop (global.get $g)) (local.set $b) (i32.const 0) (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $rotl.swap.tee (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.rotl (local.get $a) (local.get $b)) (local.set $a (local.get $b)) (local.tee $b)  (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $rotl.swap.tee.ref (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.rotl (local.get $a) (local.get $b)) (local.set $a (local.get $b)) (drop (global.get $g)) (local.tee $b)  (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $rotl.unrelated.set (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.rotl (local.get $a) (local.get $b)) (local.set $c (local.get $a)) (local.set $b) (i32.const 0) (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $rotl.unrelated.set.ref (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.rotl (local.get $a) (local.get $b)) (local.set $c (local.get $a)) (drop (global.get $g)) (local.set $b) (i32.const 0) (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $rotl.unrelated.tee (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.rotl (local.get $a) (local.get $b)) (local.set $c (local.get $a)) (local.tee $b)  (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $rotl.unrelated.tee.ref (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.rotl (local.get $a) (local.get $b)) (local.set $c (local.get $a)) (drop (global.get $g)) (local.tee $b)  (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $rotl.same_dest.set (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.rotl (local.get $a) (local.get $b)) (local.set $a (local.get $b)) (local.set $a) (i32.const 0) (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $rotl.same_dest.set.ref (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.rotl (local.get $a) (local.get $b)) (local.set $a (local.get $b)) (drop (global.get $g)) (local.set $a) (i32.const 0) (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $rotl.same_dest.tee (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.rotl (local.get $a) (local.get $b)) (local.set $a (local.get $b)) (local.tee $a)  (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $rotl.same_dest.tee.ref (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.rotl (local.get $a) (local.get $b)) (local.set $a (local.get $b)) (drop (global.get $g)) (local.tee $a)  (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $rotl.from_dest.set (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.rotl (local.get $a) (local.get $b)) (local.set $c (local.get $b)) (local.set $b) (i32.const 0) (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $rotl.from_dest.set.ref (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.rotl (local.get $a) (local.get $b)) (local.set $c (local.get $b)) (drop (global.get $g)) (local.set $b) (i32.const 0) (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $rotl.from_dest.tee (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.rotl (local.get $a) (local.get $b)) (local.set $c (local.get $b)) (local.tee $b)  (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $rotl.from_dest.tee.ref (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.rotl (local.get $a) (local.get $b)) (local.set $c (local.get $b)) (drop (global.get $g)) (local.tee $b)  (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $addimm.swap.set (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.add (local.get $a) (i32.const 7)) (local.set $a (local.get $b)) (local.set $b) (i32.const 0) (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $addimm.swap.set.ref (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.add (local.get $a) (i32.const 7)) (local.set $a (local.get $b)) (drop (global.get $g)) (local.set $b) (i32.const 0) (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $addimm.swap.tee (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.add (local.get $a) (i32.const 7)) (local.set $a (local.get $b)) (local.tee $b)  (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $addimm.swap.tee.ref (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.add (local.get $a) (i32.const 7)) (local.set $a (local.get $b)) (drop (global.get $g)) (local.tee $b)  (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $addimm.unrelated.set (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.add (local.get $a) (i32.const 7)) (local.set $c (local.get $a)) (local.set $b) (i32.const 0) (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $addimm.unrelated.set.ref (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.add (local.get $a) (i32.const 7)) (local.set $c (local.get $a)) (drop (global.get $g)) (local.set $b) (i32.const 0) (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $addimm.unrelated.tee (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.add (local.get $a) (i32.const 7)) (local.set $c (local.get $a)) (local.tee $b)  (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $addimm.unrelated.tee.ref (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.add (local.get $a) (i32.const 7)) (local.set $c (local.get $a)) (drop (global.get $g)) (local.tee $b)  (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $addimm.same_dest.set (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.add (local.get $a) (i32.const 7)) (local.set $a (local.get $b)) (local.set $a) (i32.const 0) (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $addimm.same_dest.set.ref (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.add (local.get $a) (i32.const 7)) (local.set $a (local.get $b)) (drop (global.get $g)) (local.set $a) (i32.const 0) (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $addimm.same_dest.tee (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.add (local.get $a) (i32.const 7)) (local.set $a (local.get $b)) (local.tee $a)  (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $addimm.same_dest.tee.ref (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.add (local.get $a) (i32.const 7)) (local.set $a (local.get $b)) (drop (global.get $g)) (local.tee $a)  (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $addimm.from_dest.set (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.add (local.get $a) (i32.const 7)) (local.set $c (local.get $b)) (local.set $b) (i32.const 0) (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $addimm.from_dest.set.ref (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.add (local.get $a) (i32.const 7)) (local.set $c (local.get $b)) (drop (global.get $g)) (local.set $b) (i32.const 0) (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $addimm.from_dest.tee (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.add (local.get $a) (i32.const 7)) (local.set $c (local.get $b)) (local.tee $b)  (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $addimm.from_dest.tee.ref (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.add (local.get $a) (i32.const 7)) (local.set $c (local.get $b)) (drop (global.get $g)) (local.tee $b)  (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $load.swap.set (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.load (i32.const 0)) (local.set $a (local.get $b)) (local.set $b) (i32.const 0) (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $load.swap.set.ref (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.load (i32.const 0)) (local.set $a (local.get $b)) (drop (global.get $g)) (local.set $b) (i32.const 0) (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $load.swap.tee (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.load (i32.const 0)) (local.set $a (local.get $b)) (local.tee $b)  (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $load.swap.tee.ref (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.load (i32.const 0)) (local.set $a (local.get $b)) (drop (global.get $g)) (local.tee $b)  (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $load.unrelated.set (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.load (i32.const 0)) (local.set $c (local.get $a)) (local.set $b) (i32.const 0) (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $load.unrelated.set.ref (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.load (i32.const 0)) (local.set $c (local.get $a)) (drop (global.get $g)) (local.set $b) (i32.const 0) (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $load.unrelated.tee (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.load (i32.const 0)) (local.set $c (local.get $a)) (local.tee $b)  (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $load.unrelated.tee.ref (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.load (i32.const 0)) (local.set $c (local.get $a)) (drop (global.get $g)) (local.tee $b)  (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $load.same_dest.set (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.load (i32.const 0)) (local.set $a (local.get $b)) (local.set $a) (i32.const 0) (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $load.same_dest.set.ref (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.load (i32.const 0)) (local.set $a (local.get $b)) (drop (global.get $g)) (local.set $a) (i32.const 0) (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $load.same_dest.tee (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.load (i32.const 0)) (local.set $a (local.get $b)) (local.tee $a)  (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $load.same_dest.tee.ref (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.load (i32.const 0)) (local.set $a (local.get $b)) (drop (global.get $g)) (local.tee $a)  (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $load.from_dest.set (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.load (i32.const 0)) (local.set $c (local.get $b)) (local.set $b) (i32.const 0) (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $load.from_dest.set.ref (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.load (i32.const 0)) (local.set $c (local.get $b)) (drop (global.get $g)) (local.set $b) (i32.const 0) (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $load.from_dest.tee (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.load (i32.const 0)) (local.set $c (local.get $b)) (local.tee $b)  (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $load.from_dest.tee.ref (param $a i32) (param $b i32) (result i32) (local $c i32) (i32.load (i32.const 0)) (local.set $c (local.get $b)) (drop (global.get $g)) (local.tee $b)  (i32.xor (i32.add (i32.add (i32.mul (local.get $a) (i32.const 3)) (i32.mul (local.get $b) (i32.const 5))) (local.get $c))))
  (func $fib (param $a i32) (param $b i32) (result i32) (local $c i32) (local.set $c (i32.const 10)) (loop $l (i32.add (local.get $a) (local.get $b)) (local.set $a (local.get $b))  (local.set $b) (br_if $l (i32.ne (local.tee $c (i32.sub (local.get $c) (i32.const 1))) (i32.const 0)))) (i32.add (local.get $a) (i32.mul (local.get $b) (i32.const 3))))
  (func $fib.ref (param $a i32) (param $b i32) (result i32) (local $c i32) (local.set $c (i32.const 10)) (loop $l (i32.add (local.get $a) (local.get $b)) (local.set $a (local.get $b)) (drop (global.get $g)) (local.set $b) (br_if $l (i32.ne (local.tee $c (i32.sub (local.get $c) (i32.const 1))) (i32.const 0)))) (i32.add (local.get $a) (i32.mul (local.get $b) (i32.const 3))))
  (type $f (func (param $a i32) (param $b i32) (result i32)))
  (table funcref (elem $add.swap.set $add.swap.set.ref $add.swap.tee $add.swap.tee.ref $add.unrelated.set $add.unrelated.set.ref $add.unrelated.tee $add.unrelated.tee.ref $add.same_dest.set $add.same_dest.set.ref $add.same_dest.tee $add.same_dest.tee.ref $add.from_dest.set $add.from_dest.set.ref $add.from_dest.tee $add.from_dest.tee.ref $sub.swap.set $sub.swap.set.ref $sub.swap.tee $sub.swap.tee.ref $sub.unrelated.set $sub.unrelated.set.ref $sub.unrelated.tee $sub.unrelated.tee.ref $sub.same_dest.set $sub.same_dest.set.ref $sub.same_dest.tee $sub.same_dest.tee.ref $sub.from_dest.set $sub.from_dest.set.ref $sub.from_dest.tee $sub.from_dest.tee.ref $rotl.swap.set $rotl.swap.set.ref $rotl.swap.tee $rotl.swap.tee.ref $rotl.unrelated.set $rotl.unrelated.set.ref $rotl.unrelated.tee $rotl.unrelated.tee.ref $rotl.same_dest.set $rotl.same_dest.set.ref $rotl.same_dest.tee $rotl.same_dest.tee.ref $rotl.from_dest.set $rotl.from_dest.set.ref $rotl.from_dest.tee $rotl.from_dest.tee.ref $addimm.swap.set $addimm.swap.set.ref $addimm.swap.tee $addimm.swap.tee.ref $addimm.unrelated.set $addimm.unrelated.set.ref $addimm.unrelated.tee $addimm.unrelated.tee.ref $addimm.same_dest.set $addimm.same_dest.set.ref $addimm.same_dest.tee $addimm.same_dest.tee.ref $addimm.from_dest.set $addimm.from_dest.set.ref $addimm.from_dest.tee $addimm.from_dest.tee.ref $load.swap.set $load.swap.set.ref $load.swap.tee $load.swap.tee.ref $load.unrelated.set $load.unrelated.set.ref $load.unrelated.tee $load.unrelated.tee.ref $load.same_dest.set $load.same_dest.set.ref $load.same_dest.tee $load.same_dest.tee.ref $load.from_dest.set $load.from_dest.set.ref $load.from_dest.tee $load.from_dest.tee.ref $fib $fib.ref))
  (func (export "check") (param $k i32) (result i32) (local $i i32) (local $j i32) (local $n i32) (local $f i32) (local $x i32) (local $y i32)
    (local.set $f (i32.shl (local.get $k) (i32.const 1)))
    (loop $li
      (local.set $x (i32.load (i32.mul (local.get $i) (i32.const 4))))
      (local.set $j (i32.const 0))
      (loop $lj
        (local.set $y (i32.load (i32.mul (local.get $j) (i32.const 4))))
        (if (i32.ne (call_indirect (type $f) (local.get $x) (local.get $y) (local.get $f))
                    (call_indirect (type $f) (local.get $x) (local.get $y) (i32.add (local.get $f) (i32.const 1))))
          (then (local.set $n (i32.add (local.get $n) (i32.const 1)))))
        (br_if $lj (i32.lt_u (local.tee $j (i32.add (local.get $j) (i32.const 1))) (i32.const 7))))
      (br_if $li (i32.lt_u (local.tee $i (i32.add (local.get $i) (i32.const 1))) (i32.const 7))))
    (local.get $n))
)
(assert_return (invoke "check" (i32.const 0)) (i32.const 0)) ;; i32 add.swap.set
(assert_return (invoke "check" (i32.const 1)) (i32.const 0)) ;; i32 add.swap.tee
(assert_return (invoke "check" (i32.const 2)) (i32.const 0)) ;; i32 add.unrelated.set
(assert_return (invoke "check" (i32.const 3)) (i32.const 0)) ;; i32 add.unrelated.tee
(assert_return (invoke "check" (i32.const 4)) (i32.const 0)) ;; i32 add.same_dest.set
(assert_return (invoke "check" (i32.const 5)) (i32.const 0)) ;; i32 add.same_dest.tee
(assert_return (invoke "check" (i32.const 6)) (i32.const 0)) ;; i32 add.from_dest.set
(assert_return (invoke "check" (i32.const 7)) (i32.const 0)) ;; i32 add.from_dest.tee
(assert_return (invoke "check" (i32.const 8)) (i32.const 0)) ;; i32 sub.swap.set
(assert_return (invoke "check" (i32.const 9)) (i32.const 0)) ;; i32 sub.swap.tee
(assert_return (invoke "check" (i32.const 10)) (i32.const 0)) ;; i32 sub.unrelated.set
(assert_return (invoke "check" (i32.const 11)) (i32.const 0)) ;; i32 sub.unrelated.tee
(assert_return (invoke "check" (i32.const 12)) (i32.const 0)) ;; i32 sub.same_dest.set
(assert_return (invoke "check" (i32.const 13)) (i32.const 0)) ;; i32 sub.same_dest.tee
(assert_return (invoke "check" (i32.const 14)) (i32.const 0)) ;; i32 sub.from_dest.set
(assert_return (invoke "check" (i32.const 15)) (i32.const 0)) ;; i32 sub.from_dest.tee
(assert_return (invoke "check" (i32.const 16)) (i32.const 0)) ;; i32 rotl.swap.set
(assert_return (invoke "check" (i32.const 17)) (i32.const 0)) ;; i32 rotl.swap.tee
(assert_return (invoke "check" (i32.const 18)) (i32.const 0)) ;; i32 rotl.unrelated.set
(assert_return (invoke "check" (i32.const 19)) (i32.const 0)) ;; i32 rotl.unrelated.tee
(assert_return (invoke "check" (i32.const 20)) (i32.const 0)) ;; i32 rotl.same_dest.set
(assert_return (invoke "check" (i32.const 21)) (i32.const 0)) ;; i32 rotl.same_dest.tee
(assert_return (invoke "check" (i32.const 22)) (i32.const 0)) ;; i32 rotl.from_dest.set
(assert_return (invoke "check" (i32.const 23)) (i32.const 0)) ;; i32 rotl.from_dest.tee
(assert_return (invoke "check" (i32.const 24)) (i32.const 0)) ;; i32 addimm.swap.set
(assert_return (invoke "check" (i32.const 25)) (i32.const 0)) ;; i32 addimm.swap.tee
(assert_return (invoke "check" (i32.const 26)) (i32.const 0)) ;; i32 addimm.unrelated.set
(assert_return (invoke "check" (i32.const 27)) (i32.const 0)) ;; i32 addimm.unrelated.tee
(assert_return (invoke "check" (i32.const 28)) (i32.const 0)) ;; i32 addimm.same_dest.set
(assert_return (invoke "check" (i32.const 29)) (i32.const 0)) ;; i32 addimm.same_dest.tee
(assert_return (invoke "check" (i32.const 30)) (i32.const 0)) ;; i32 addimm.from_dest.set
(assert_return (invoke "check" (i32.const 31)) (i32.const 0)) ;; i32 addimm.from_dest.tee
(assert_return (invoke "check" (i32.const 32)) (i32.const 0)) ;; i32 load.swap.set
(assert_return (invoke "check" (i32.const 33)) (i32.const 0)) ;; i32 load.swap.tee
(assert_return (invoke "check" (i32.const 34)) (i32.const 0)) ;; i32 load.unrelated.set
(assert_return (invoke "check" (i32.const 35)) (i32.const 0)) ;; i32 load.unrelated.tee
(assert_return (invoke "check" (i32.const 36)) (i32.const 0)) ;; i32 load.same_dest.set
(assert_return (invoke "check" (i32.const 37)) (i32.const 0)) ;; i32 load.same_dest.tee
(assert_return (invoke "check" (i32.const 38)) (i32.const 0)) ;; i32 load.from_dest.set
(assert_return (invoke "check" (i32.const 39)) (i32.const 0)) ;; i32 load.from_dest.tee
(assert_return (invoke "check" (i32.const 40)) (i32.const 0)) ;; i32 fib

(module
  (memory 1)
  (data (i32.const 0) "\00\00\00\00\00\00\00\00\01\00\00\00\00\00\00\00\ff\ff\ff\ff\ff\ff\ff\ff\05\00\00\00\00\00\00\00\ff\ff\ff\ff\ff\ff\ff\7f\00\00\00\00\00\00\00\80\f0\de\bc\9a\78\56\34\12")
  (global $g (mut i32) (i32.const 0))
  (func $add.swap.set (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.add (local.get $a) (local.get $b)) (local.set $a (local.get $b)) (local.set $b) (i64.const 0) (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $add.swap.set.ref (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.add (local.get $a) (local.get $b)) (local.set $a (local.get $b)) (drop (global.get $g)) (local.set $b) (i64.const 0) (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $add.swap.tee (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.add (local.get $a) (local.get $b)) (local.set $a (local.get $b)) (local.tee $b)  (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $add.swap.tee.ref (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.add (local.get $a) (local.get $b)) (local.set $a (local.get $b)) (drop (global.get $g)) (local.tee $b)  (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $add.unrelated.set (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.add (local.get $a) (local.get $b)) (local.set $c (local.get $a)) (local.set $b) (i64.const 0) (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $add.unrelated.set.ref (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.add (local.get $a) (local.get $b)) (local.set $c (local.get $a)) (drop (global.get $g)) (local.set $b) (i64.const 0) (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $add.unrelated.tee (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.add (local.get $a) (local.get $b)) (local.set $c (local.get $a)) (local.tee $b)  (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $add.unrelated.tee.ref (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.add (local.get $a) (local.get $b)) (local.set $c (local.get $a)) (drop (global.get $g)) (local.tee $b)  (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $add.same_dest.set (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.add (local.get $a) (local.get $b)) (local.set $a (local.get $b)) (local.set $a) (i64.const 0) (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $add.same_dest.set.ref (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.add (local.get $a) (local.get $b)) (local.set $a (local.get $b)) (drop (global.get $g)) (local.set $a) (i64.const 0) (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $add.same_dest.tee (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.add (local.get $a) (local.get $b)) (local.set $a (local.get $b)) (local.tee $a)  (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $add.same_dest.tee.ref (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.add (local.get $a) (local.get $b)) (local.set $a (local.get $b)) (drop (global.get $g)) (local.tee $a)  (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $add.from_dest.set (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.add (local.get $a) (local.get $b)) (local.set $c (local.get $b)) (local.set $b) (i64.const 0) (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $add.from_dest.set.ref (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.add (local.get $a) (local.get $b)) (local.set $c (local.get $b)) (drop (global.get $g)) (local.set $b) (i64.const 0) (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $add.from_dest.tee (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.add (local.get $a) (local.get $b)) (local.set $c (local.get $b)) (local.tee $b)  (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $add.from_dest.tee.ref (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.add (local.get $a) (local.get $b)) (local.set $c (local.get $b)) (drop (global.get $g)) (local.tee $b)  (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $sub.swap.set (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.sub (local.get $a) (local.get $b)) (local.set $a (local.get $b)) (local.set $b) (i64.const 0) (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $sub.swap.set.ref (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.sub (local.get $a) (local.get $b)) (local.set $a (local.get $b)) (drop (global.get $g)) (local.set $b) (i64.const 0) (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $sub.swap.tee (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.sub (local.get $a) (local.get $b)) (local.set $a (local.get $b)) (local.tee $b)  (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $sub.swap.tee.ref (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.sub (local.get $a) (local.get $b)) (local.set $a (local.get $b)) (drop (global.get $g)) (local.tee $b)  (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $sub.unrelated.set (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.sub (local.get $a) (local.get $b)) (local.set $c (local.get $a)) (local.set $b) (i64.const 0) (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $sub.unrelated.set.ref (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.sub (local.get $a) (local.get $b)) (local.set $c (local.get $a)) (drop (global.get $g)) (local.set $b) (i64.const 0) (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $sub.unrelated.tee (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.sub (local.get $a) (local.get $b)) (local.set $c (local.get $a)) (local.tee $b)  (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $sub.unrelated.tee.ref (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.sub (local.get $a) (local.get $b)) (local.set $c (local.get $a)) (drop (global.get $g)) (local.tee $b)  (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $sub.same_dest.set (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.sub (local.get $a) (local.get $b)) (local.set $a (local.get $b)) (local.set $a) (i64.const 0) (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $sub.same_dest.set.ref (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.sub (local.get $a) (local.get $b)) (local.set $a (local.get $b)) (drop (global.get $g)) (local.set $a) (i64.const 0) (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $sub.same_dest.tee (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.sub (local.get $a) (local.get $b)) (local.set $a (local.get $b)) (local.tee $a)  (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $sub.same_dest.tee.ref (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.sub (local.get $a) (local.get $b)) (local.set $a (local.get $b)) (drop (global.get $g)) (local.tee $a)  (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $sub.from_dest.set (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.sub (local.get $a) (local.get $b)) (local.set $c (local.get $b)) (local.set $b) (i64.const 0) (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $sub.from_dest.set.ref (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.sub (local.get $a) (local.get $b)) (local.set $c (local.get $b)) (drop (global.get $g)) (local.set $b) (i64.const 0) (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $sub.from_dest.tee (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.sub (local.get $a) (local.get $b)) (local.set $c (local.get $b)) (local.tee $b)  (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $sub.from_dest.tee.ref (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.sub (local.get $a) (local.get $b)) (local.set $c (local.get $b)) (drop (global.get $g)) (local.tee $b)  (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $rotl.swap.set (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.rotl (local.get $a) (local.get $b)) (local.set $a (local.get $b)) (local.set $b) (i64.const 0) (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $rotl.swap.set.ref (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.rotl (local.get $a) (local.get $b)) (local.set $a (local.get $b)) (drop (global.get $g)) (local.set $b) (i64.const 0) (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $rotl.swap.tee (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.rotl (local.get $a) (local.get $b)) (local.set $a (local.get $b)) (local.tee $b)  (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $rotl.swap.tee.ref (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.rotl (local.get $a) (local.get $b)) (local.set $a (local.get $b)) (drop (global.get $g)) (local.tee $b)  (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $rotl.unrelated.set (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.rotl (local.get $a) (local.get $b)) (local.set $c (local.get $a)) (local.set $b) (i64.const 0) (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $rotl.unrelated.set.ref (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.rotl (local.get $a) (local.get $b)) (local.set $c (local.get $a)) (drop (global.get $g)) (local.set $b) (i64.const 0) (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $rotl.unrelated.tee (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.rotl (local.get $a) (local.get $b)) (local.set $c (local.get $a)) (local.tee $b)  (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $rotl.unrelated.tee.ref (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.rotl (local.get $a) (local.get $b)) (local.set $c (local.get $a)) (drop (global.get $g)) (local.tee $b)  (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $rotl.same_dest.set (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.rotl (local.get $a) (local.get $b)) (local.set $a (local.get $b)) (local.set $a) (i64.const 0) (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $rotl.same_dest.set.ref (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.rotl (local.get $a) (local.get $b)) (local.set $a (local.get $b)) (drop (global.get $g)) (local.set $a) (i64.const 0) (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $rotl.same_dest.tee (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.rotl (local.get $a) (local.get $b)) (local.set $a (local.get $b)) (local.tee $a)  (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $rotl.same_dest.tee.ref (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.rotl (local.get $a) (local.get $b)) (local.set $a (local.get $b)) (drop (global.get $g)) (local.tee $a)  (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $rotl.from_dest.set (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.rotl (local.get $a) (local.get $b)) (local.set $c (local.get $b)) (local.set $b) (i64.const 0) (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $rotl.from_dest.set.ref (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.rotl (local.get $a) (local.get $b)) (local.set $c (local.get $b)) (drop (global.get $g)) (local.set $b) (i64.const 0) (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $rotl.from_dest.tee (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.rotl (local.get $a) (local.get $b)) (local.set $c (local.get $b)) (local.tee $b)  (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $rotl.from_dest.tee.ref (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.rotl (local.get $a) (local.get $b)) (local.set $c (local.get $b)) (drop (global.get $g)) (local.tee $b)  (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $addimm.swap.set (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.add (local.get $a) (i64.const 7)) (local.set $a (local.get $b)) (local.set $b) (i64.const 0) (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $addimm.swap.set.ref (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.add (local.get $a) (i64.const 7)) (local.set $a (local.get $b)) (drop (global.get $g)) (local.set $b) (i64.const 0) (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $addimm.swap.tee (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.add (local.get $a) (i64.const 7)) (local.set $a (local.get $b)) (local.tee $b)  (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $addimm.swap.tee.ref (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.add (local.get $a) (i64.const 7)) (local.set $a (local.get $b)) (drop (global.get $g)) (local.tee $b)  (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $addimm.unrelated.set (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.add (local.get $a) (i64.const 7)) (local.set $c (local.get $a)) (local.set $b) (i64.const 0) (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $addimm.unrelated.set.ref (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.add (local.get $a) (i64.const 7)) (local.set $c (local.get $a)) (drop (global.get $g)) (local.set $b) (i64.const 0) (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $addimm.unrelated.tee (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.add (local.get $a) (i64.const 7)) (local.set $c (local.get $a)) (local.tee $b)  (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $addimm.unrelated.tee.ref (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.add (local.get $a) (i64.const 7)) (local.set $c (local.get $a)) (drop (global.get $g)) (local.tee $b)  (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $addimm.same_dest.set (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.add (local.get $a) (i64.const 7)) (local.set $a (local.get $b)) (local.set $a) (i64.const 0) (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $addimm.same_dest.set.ref (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.add (local.get $a) (i64.const 7)) (local.set $a (local.get $b)) (drop (global.get $g)) (local.set $a) (i64.const 0) (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $addimm.same_dest.tee (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.add (local.get $a) (i64.const 7)) (local.set $a (local.get $b)) (local.tee $a)  (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $addimm.same_dest.tee.ref (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.add (local.get $a) (i64.const 7)) (local.set $a (local.get $b)) (drop (global.get $g)) (local.tee $a)  (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $addimm.from_dest.set (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.add (local.get $a) (i64.const 7)) (local.set $c (local.get $b)) (local.set $b) (i64.const 0) (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $addimm.from_dest.set.ref (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.add (local.get $a) (i64.const 7)) (local.set $c (local.get $b)) (drop (global.get $g)) (local.set $b) (i64.const 0) (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $addimm.from_dest.tee (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.add (local.get $a) (i64.const 7)) (local.set $c (local.get $b)) (local.tee $b)  (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $addimm.from_dest.tee.ref (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.add (local.get $a) (i64.const 7)) (local.set $c (local.get $b)) (drop (global.get $g)) (local.tee $b)  (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $load.swap.set (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.load (i32.const 0)) (local.set $a (local.get $b)) (local.set $b) (i64.const 0) (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $load.swap.set.ref (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.load (i32.const 0)) (local.set $a (local.get $b)) (drop (global.get $g)) (local.set $b) (i64.const 0) (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $load.swap.tee (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.load (i32.const 0)) (local.set $a (local.get $b)) (local.tee $b)  (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $load.swap.tee.ref (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.load (i32.const 0)) (local.set $a (local.get $b)) (drop (global.get $g)) (local.tee $b)  (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $load.unrelated.set (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.load (i32.const 0)) (local.set $c (local.get $a)) (local.set $b) (i64.const 0) (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $load.unrelated.set.ref (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.load (i32.const 0)) (local.set $c (local.get $a)) (drop (global.get $g)) (local.set $b) (i64.const 0) (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $load.unrelated.tee (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.load (i32.const 0)) (local.set $c (local.get $a)) (local.tee $b)  (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $load.unrelated.tee.ref (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.load (i32.const 0)) (local.set $c (local.get $a)) (drop (global.get $g)) (local.tee $b)  (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $load.same_dest.set (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.load (i32.const 0)) (local.set $a (local.get $b)) (local.set $a) (i64.const 0) (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $load.same_dest.set.ref (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.load (i32.const 0)) (local.set $a (local.get $b)) (drop (global.get $g)) (local.set $a) (i64.const 0) (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $load.same_dest.tee (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.load (i32.const 0)) (local.set $a (local.get $b)) (local.tee $a)  (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $load.same_dest.tee.ref (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.load (i32.const 0)) (local.set $a (local.get $b)) (drop (global.get $g)) (local.tee $a)  (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $load.from_dest.set (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.load (i32.const 0)) (local.set $c (local.get $b)) (local.set $b) (i64.const 0) (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $load.from_dest.set.ref (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.load (i32.const 0)) (local.set $c (local.get $b)) (drop (global.get $g)) (local.set $b) (i64.const 0) (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $load.from_dest.tee (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.load (i32.const 0)) (local.set $c (local.get $b)) (local.tee $b)  (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $load.from_dest.tee.ref (param $a i64) (param $b i64) (result i64) (local $c i64) (i64.load (i32.const 0)) (local.set $c (local.get $b)) (drop (global.get $g)) (local.tee $b)  (i64.xor (i64.add (i64.add (i64.mul (local.get $a) (i64.const 3)) (i64.mul (local.get $b) (i64.const 5))) (local.get $c))))
  (func $fib (param $a i64) (param $b i64) (result i64) (local $c i64) (local.set $c (i64.const 10)) (loop $l (i64.add (local.get $a) (local.get $b)) (local.set $a (local.get $b))  (local.set $b) (br_if $l (i64.ne (local.tee $c (i64.sub (local.get $c) (i64.const 1))) (i64.const 0)))) (i64.add (local.get $a) (i64.mul (local.get $b) (i64.const 3))))
  (func $fib.ref (param $a i64) (param $b i64) (result i64) (local $c i64) (local.set $c (i64.const 10)) (loop $l (i64.add (local.get $a) (local.get $b)) (local.set $a (local.get $b)) (drop (global.get $g)) (local.set $b) (br_if $l (i64.ne (local.tee $c (i64.sub (local.get $c) (i64.const 1))) (i64.const 0)))) (i64.add (local.get $a) (i64.mul (local.get $b) (i64.const 3))))
  (type $f (func (param $a i64) (param $b i64) (result i64)))
  (table funcref (elem $add.swap.set $add.swap.set.ref $add.swap.tee $add.swap.tee.ref $add.unrelated.set $add.unrelated.set.ref $add.unrelated.tee $add.unrelated.tee.ref $add.same_dest.set $add.same_dest.set.ref $add.same_dest.tee $add.same_dest.tee.ref $add.from_dest.set $add.from_dest.set.ref $add.from_dest.tee $add.from_dest.tee.ref $sub.swap.set $sub.swap.set.ref $sub.swap.tee $sub.swap.tee.ref $sub.unrelated.set $sub.unrelated.set.ref $sub.unrelated.tee $sub.unrelated.tee.ref $sub.same_dest.set $sub.same_dest.set.ref $sub.same_dest.tee $sub.same_dest.tee.ref $sub.from_dest.set $sub.from_dest.set.ref $sub.from_dest.tee $sub.from_dest.tee.ref $rotl.swap.set $rotl.swap.set.ref $rotl.swap.tee $rotl.swap.tee.ref $rotl.unrelated.set $rotl.unrelated.set.ref $rotl.unrelated.tee $rotl.unrelated.tee.ref $rotl.same_dest.set $rotl.same_dest.set.ref $rotl.same_dest.tee $rotl.same_dest.tee.ref $rotl.from_dest.set $rotl.from_dest.set.ref $rotl.from_dest.tee $rotl.from_dest.tee.ref $addimm.swap.set $addimm.swap.set.ref $addimm.swap.tee $addimm.swap.tee.ref $addimm.unrelated.set $addimm.unrelated.set.ref $addimm.unrelated.tee $addimm.unrelated.tee.ref $addimm.same_dest.set $addimm.same_dest.set.ref $addimm.same_dest.tee $addimm.same_dest.tee.ref $addimm.from_dest.set $addimm.from_dest.set.ref $addimm.from_dest.tee $addimm.from_dest.tee.ref $load.swap.set $load.swap.set.ref $load.swap.tee $load.swap.tee.ref $load.unrelated.set $load.unrelated.set.ref $load.unrelated.tee $load.unrelated.tee.ref $load.same_dest.set $load.same_dest.set.ref $load.same_dest.tee $load.same_dest.tee.ref $load.from_dest.set $load.from_dest.set.ref $load.from_dest.tee $load.from_dest.tee.ref $fib $fib.ref))
  (func (export "check") (param $k i32) (result i32) (local $i i32) (local $j i32) (local $n i32) (local $f i32) (local $x i64) (local $y i64)
    (local.set $f (i32.shl (local.get $k) (i32.const 1)))
    (loop $li
      (local.set $x (i64.load (i32.mul (local.get $i) (i32.const 8))))
      (local.set $j (i32.const 0))
      (loop $lj
        (local.set $y (i64.load (i32.mul (local.get $j) (i32.const 8))))
        (if (i64.ne (call_indirect (type $f) (local.get $x) (local.get $y) (local.get $f))
                    (call_indirect (type $f) (local.get $x) (local.get $y) (i32.add (local.get $f) (i32.const 1))))
          (then (local.set $n (i32.add (local.get $n) (i32.const 1)))))
        (br_if $lj (i32.lt_u (local.tee $j (i32.add (local.get $j) (i32.const 1))) (i32.const 7))))
      (br_if $li (i32.lt_u (local.tee $i (i32.add (local.get $i) (i32.const 1))) (i32.const 7))))
    (local.get $n))
)
(assert_return (invoke "check" (i32.const 0)) (i32.const 0)) ;; i64 add.swap.set
(assert_return (invoke "check" (i32.const 1)) (i32.const 0)) ;; i64 add.swap.tee
(assert_return (invoke "check" (i32.const 2)) (i32.const 0)) ;; i64 add.unrelated.set
(assert_return (invoke "check" (i32.const 3)) (i32.const 0)) ;; i64 add.unrelated.tee
(assert_return (invoke "check" (i32.const 4)) (i32.const 0)) ;; i64 add.same_dest.set
(assert_return (invoke "check" (i32.const 5)) (i32.const 0)) ;; i64 add.same_dest.tee
(assert_return (invoke "check" (i32.const 6)) (i32.const 0)) ;; i64 add.from_dest.set
(assert_return (invoke "check" (i32.const 7)) (i32.const 0)) ;; i64 add.from_dest.tee
(assert_return (invoke "check" (i32.const 8)) (i32.const 0)) ;; i64 sub.swap.set
(assert_return (invoke "check" (i32.const 9)) (i32.const 0)) ;; i64 sub.swap.tee
(assert_return (invoke "check" (i32.const 10)) (i32.const 0)) ;; i64 sub.unrelated.set
(assert_return (invoke "check" (i32.const 11)) (i32.const 0)) ;; i64 sub.unrelated.tee
(assert_return (invoke "check" (i32.const 12)) (i32.const 0)) ;; i64 sub.same_dest.set
(assert_return (invoke "check" (i32.const 13)) (i32.const 0)) ;; i64 sub.same_dest.tee
(assert_return (invoke "check" (i32.const 14)) (i32.const 0)) ;; i64 sub.from_dest.set
(assert_return (invoke "check" (i32.const 15)) (i32.const 0)) ;; i64 sub.from_dest.tee
(assert_return (invoke "check" (i32.const 16)) (i32.const 0)) ;; i64 rotl.swap.set
(assert_return (invoke "check" (i32.const 17)) (i32.const 0)) ;; i64 rotl.swap.tee
(assert_return (invoke "check" (i32.const 18)) (i32.const 0)) ;; i64 rotl.unrelated.set
(assert_return (invoke "check" (i32.const 19)) (i32.const 0)) ;; i64 rotl.unrelated.tee
(assert_return (invoke "check" (i32.const 20)) (i32.const 0)) ;; i64 rotl.same_dest.set
(assert_return (invoke "check" (i32.const 21)) (i32.const 0)) ;; i64 rotl.same_dest.tee
(assert_return (invoke "check" (i32.const 22)) (i32.const 0)) ;; i64 rotl.from_dest.set
(assert_return (invoke "check" (i32.const 23)) (i32.const 0)) ;; i64 rotl.from_dest.tee
(assert_return (invoke "check" (i32.const 24)) (i32.const 0)) ;; i64 addimm.swap.set
(assert_return (invoke "check" (i32.const 25)) (i32.const 0)) ;; i64 addimm.swap.tee
(assert_return (invoke "check" (i32.const 26)) (i32.const 0)) ;; i64 addimm.unrelated.set
(assert_return (invoke "check" (i32.const 27)) (i32.const 0)) ;; i64 addimm.unrelated.tee
(assert_return (invoke "check" (i32.const 28)) (i32.const 0)) ;; i64 addimm.same_dest.set
(assert_return (invoke "check" (i32.const 29)) (i32.const 0)) ;; i64 addimm.same_dest.tee
(assert_return (invoke "check" (i32.const 30)) (i32.const 0)) ;; i64 addimm.from_dest.set
(assert_return (invoke "check" (i32.const 31)) (i32.const 0)) ;; i64 addimm.from_dest.tee
(assert_return (invoke "check" (i32.const 32)) (i32.const 0)) ;; i64 load.swap.set
(assert_return (invoke "check" (i32.const 33)) (i32.const 0)) ;; i64 load.swap.tee
(assert_return (invoke "check" (i32.const 34)) (i32.const 0)) ;; i64 load.unrelated.set
(assert_return (invoke "check" (i32.const 35)) (i32.const 0)) ;; i64 load.unrelated.tee
(assert_return (invoke "check" (i32.const 36)) (i32.const 0)) ;; i64 load.same_dest.set
(assert_return (invoke "check" (i32.const 37)) (i32.const 0)) ;; i64 load.same_dest.tee
(assert_return (invoke "check" (i32.const 38)) (i32.const 0)) ;; i64 load.from_dest.set
(assert_return (invoke "check" (i32.const 39)) (i32.const 0)) ;; i64 load.from_dest.tee
(assert_return (invoke "check" (i32.const 40)) (i32.const 0)) ;; i64 fib

