// This file is generated by Utilities/generate_inst_dispatch.swift
extension ExecutionState {
    @inline(__always)
    mutating func doExecute(_ instruction: Instruction, sp: inout Sp, r0: inout R0, pc: inout Pc, md: inout Md, ms: inout Ms) throws -> Bool {
        switch instruction {
        case .copyStack(let copyStackOperand):
            self.copyStack(sp: sp, copyStackOperand: copyStackOperand)
        case .copyR0ToStackI32(let dest):
            self.copyR0ToStackI32(sp: sp, r0: r0, dest: dest)
        case .copyR0ToStackI64(let dest):
            self.copyR0ToStackI64(sp: sp, r0: r0, dest: dest)
        case .copyR0ToStackF32(let dest):
            self.copyR0ToStackF32(sp: sp, r0: r0, dest: dest)
        case .copyR0ToStackF64(let dest):
            self.copyR0ToStackF64(sp: sp, r0: r0, dest: dest)
        case .globalGet(let globalGetOperand):
            try self.globalGet(sp: sp, globalGetOperand: globalGetOperand)
        case .globalSet(let globalSetOperand):
            try self.globalSet(sp: sp, globalSetOperand: globalSetOperand)
        case .call(let callOperand):
            try self.call(sp: &sp, pc: &pc, md: &md, ms: &ms, callOperand: callOperand)
            return false
        case .compilingCall(let compilingCallOperand):
            try self.compilingCall(sp: &sp, pc: &pc, compilingCallOperand: compilingCallOperand)
            return false
        case .internalCall(let internalCallOperand):
            try self.internalCall(sp: &sp, pc: &pc, internalCallOperand: internalCallOperand)
            return false
        case .callIndirect(let callIndirectOperand):
            try self.callIndirect(sp: &sp, pc: &pc, md: &md, ms: &ms, callIndirectOperand: callIndirectOperand)
            return false
        case .unreachable:
            try self.unreachable(sp: sp, pc: &pc)
            return true
        case .nop:
            try self.nop(sp: sp, pc: &pc)
            return true
        case .ifThen(let ifOperand):
            self.ifThen(sp: sp, pc: &pc, ifOperand: ifOperand)
            return true
        case .br(let offset):
            try self.br(sp: sp, pc: &pc, offset: offset)
            return true
        case .brIf(let brIfOperand):
            try self.brIf(sp: sp, pc: &pc, brIfOperand: brIfOperand)
            return true
        case .brIfNot(let brIfOperand):
            try self.brIfNot(sp: sp, pc: &pc, brIfOperand: brIfOperand)
            return true
        case .brTable(let brTableOperand):
            try self.brTable(sp: sp, pc: &pc, brTableOperand: brTableOperand)
            return true
        case .`return`:
            try self.`return`(sp: &sp, pc: &pc, md: &md, ms: &ms)
            return false
        case .endOfExecution:
            try self.endOfExecution(sp: &sp, pc: &pc)
            return false
        case .i32Load(let loadOperand):
            try self.i32Load(sp: sp, md: md, ms: ms, loadOperand: loadOperand)
        case .i64Load(let loadOperand):
            try self.i64Load(sp: sp, md: md, ms: ms, loadOperand: loadOperand)
        case .f32Load(let loadOperand):
            try self.f32Load(sp: sp, md: md, ms: ms, loadOperand: loadOperand)
        case .f64Load(let loadOperand):
            try self.f64Load(sp: sp, md: md, ms: ms, loadOperand: loadOperand)
        case .i32Load8S(let loadOperand):
            try self.i32Load8S(sp: sp, md: md, ms: ms, loadOperand: loadOperand)
        case .i32Load8U(let loadOperand):
            try self.i32Load8U(sp: sp, md: md, ms: ms, loadOperand: loadOperand)
        case .i32Load16S(let loadOperand):
            try self.i32Load16S(sp: sp, md: md, ms: ms, loadOperand: loadOperand)
        case .i32Load16U(let loadOperand):
            try self.i32Load16U(sp: sp, md: md, ms: ms, loadOperand: loadOperand)
        case .i64Load8S(let loadOperand):
            try self.i64Load8S(sp: sp, md: md, ms: ms, loadOperand: loadOperand)
        case .i64Load8U(let loadOperand):
            try self.i64Load8U(sp: sp, md: md, ms: ms, loadOperand: loadOperand)
        case .i64Load16S(let loadOperand):
            try self.i64Load16S(sp: sp, md: md, ms: ms, loadOperand: loadOperand)
        case .i64Load16U(let loadOperand):
            try self.i64Load16U(sp: sp, md: md, ms: ms, loadOperand: loadOperand)
        case .i64Load32S(let loadOperand):
            try self.i64Load32S(sp: sp, md: md, ms: ms, loadOperand: loadOperand)
        case .i64Load32U(let loadOperand):
            try self.i64Load32U(sp: sp, md: md, ms: ms, loadOperand: loadOperand)
        case .i32Store(let storeOperand):
            try self.i32Store(sp: sp, md: md, ms: ms, storeOperand: storeOperand)
        case .i64Store(let storeOperand):
            try self.i64Store(sp: sp, md: md, ms: ms, storeOperand: storeOperand)
        case .f32Store(let storeOperand):
            try self.f32Store(sp: sp, md: md, ms: ms, storeOperand: storeOperand)
        case .f64Store(let storeOperand):
            try self.f64Store(sp: sp, md: md, ms: ms, storeOperand: storeOperand)
        case .i32Store8(let storeOperand):
            try self.i32Store8(sp: sp, md: md, ms: ms, storeOperand: storeOperand)
        case .i32Store16(let storeOperand):
            try self.i32Store16(sp: sp, md: md, ms: ms, storeOperand: storeOperand)
        case .i64Store8(let storeOperand):
            try self.i64Store8(sp: sp, md: md, ms: ms, storeOperand: storeOperand)
        case .i64Store16(let storeOperand):
            try self.i64Store16(sp: sp, md: md, ms: ms, storeOperand: storeOperand)
        case .i64Store32(let storeOperand):
            try self.i64Store32(sp: sp, md: md, ms: ms, storeOperand: storeOperand)
        case .memorySize(let memorySizeOperand):
            self.memorySize(sp: sp, memorySizeOperand: memorySizeOperand)
        case .memoryGrow(let memoryGrowOperand):
            try self.memoryGrow(sp: sp, md: &md, ms: &ms, memoryGrowOperand: memoryGrowOperand)
        case .memoryInit(let memoryInitOperand):
            try self.memoryInit(sp: sp, memoryInitOperand: memoryInitOperand)
        case .memoryDataDrop(let dataIndex):
            self.memoryDataDrop(sp: sp, dataIndex: dataIndex)
        case .memoryCopy(let memoryCopyOperand):
            try self.memoryCopy(sp: sp, memoryCopyOperand: memoryCopyOperand)
        case .memoryFill(let memoryFillOperand):
            try self.memoryFill(sp: sp, memoryFillOperand: memoryFillOperand)
        case .numericConst(let constOperand):
            self.numericConst(sp: sp, constOperand: constOperand)
        case .numericFloatUnary(let floatUnary, let unaryOperand):
            self.numericFloatUnary(sp: sp, floatUnary: floatUnary, unaryOperand: unaryOperand)
        case .numericIntBinary(let intBinary, let binaryOperand):
            try self.numericIntBinary(sp: sp, intBinary: intBinary, binaryOperand: binaryOperand)
        case .numericFloatBinary(let floatBinary, let binaryOperand):
            self.numericFloatBinary(sp: sp, floatBinary: floatBinary, binaryOperand: binaryOperand)
        case .numericConversion(let conversion, let unaryOperand):
            try self.numericConversion(sp: sp, conversion: conversion, unaryOperand: unaryOperand)
        case .i32AddSS(let lhs, let rhs):
            self.i32AddSS(sp: sp, r0: &r0, lhs: lhs, rhs: rhs)
        case .i32AddSR(let lhs):
            self.i32AddSR(sp: sp, r0: &r0, lhs: lhs)
        case .i64AddSS(let lhs, let rhs):
            self.i64AddSS(sp: sp, r0: &r0, lhs: lhs, rhs: rhs)
        case .i64AddSR(let lhs):
            self.i64AddSR(sp: sp, r0: &r0, lhs: lhs)
        case .i32MulSS(let lhs, let rhs):
            self.i32MulSS(sp: sp, r0: &r0, lhs: lhs, rhs: rhs)
        case .i32MulSR(let lhs):
            self.i32MulSR(sp: sp, r0: &r0, lhs: lhs)
        case .i64MulSS(let lhs, let rhs):
            self.i64MulSS(sp: sp, r0: &r0, lhs: lhs, rhs: rhs)
        case .i64MulSR(let lhs):
            self.i64MulSR(sp: sp, r0: &r0, lhs: lhs)
        case .i32AndSS(let lhs, let rhs):
            self.i32AndSS(sp: sp, r0: &r0, lhs: lhs, rhs: rhs)
        case .i32AndSR(let lhs):
            self.i32AndSR(sp: sp, r0: &r0, lhs: lhs)
        case .i64AndSS(let lhs, let rhs):
            self.i64AndSS(sp: sp, r0: &r0, lhs: lhs, rhs: rhs)
        case .i64AndSR(let lhs):
            self.i64AndSR(sp: sp, r0: &r0, lhs: lhs)
        case .i32OrSS(let lhs, let rhs):
            self.i32OrSS(sp: sp, r0: &r0, lhs: lhs, rhs: rhs)
        case .i32OrSR(let lhs):
            self.i32OrSR(sp: sp, r0: &r0, lhs: lhs)
        case .i64OrSS(let lhs, let rhs):
            self.i64OrSS(sp: sp, r0: &r0, lhs: lhs, rhs: rhs)
        case .i64OrSR(let lhs):
            self.i64OrSR(sp: sp, r0: &r0, lhs: lhs)
        case .i32XorSS(let lhs, let rhs):
            self.i32XorSS(sp: sp, r0: &r0, lhs: lhs, rhs: rhs)
        case .i32XorSR(let lhs):
            self.i32XorSR(sp: sp, r0: &r0, lhs: lhs)
        case .i64XorSS(let lhs, let rhs):
            self.i64XorSS(sp: sp, r0: &r0, lhs: lhs, rhs: rhs)
        case .i64XorSR(let lhs):
            self.i64XorSR(sp: sp, r0: &r0, lhs: lhs)
        case .i32SubSS(let lhs, let rhs):
            self.i32SubSS(sp: sp, r0: &r0, lhs: lhs, rhs: rhs)
        case .i32SubSR(let lhs):
            self.i32SubSR(sp: sp, r0: &r0, lhs: lhs)
        case .i32SubRS(let rhs):
            self.i32SubRS(sp: sp, r0: &r0, rhs: rhs)
        case .i64SubSS(let lhs, let rhs):
            self.i64SubSS(sp: sp, r0: &r0, lhs: lhs, rhs: rhs)
        case .i64SubSR(let lhs):
            self.i64SubSR(sp: sp, r0: &r0, lhs: lhs)
        case .i64SubRS(let rhs):
            self.i64SubRS(sp: sp, r0: &r0, rhs: rhs)
        case .i32ShlSS(let lhs, let rhs):
            self.i32ShlSS(sp: sp, r0: &r0, lhs: lhs, rhs: rhs)
        case .i32ShlSR(let lhs):
            self.i32ShlSR(sp: sp, r0: &r0, lhs: lhs)
        case .i32ShlRS(let rhs):
            self.i32ShlRS(sp: sp, r0: &r0, rhs: rhs)
        case .i64ShlSS(let lhs, let rhs):
            self.i64ShlSS(sp: sp, r0: &r0, lhs: lhs, rhs: rhs)
        case .i64ShlSR(let lhs):
            self.i64ShlSR(sp: sp, r0: &r0, lhs: lhs)
        case .i64ShlRS(let rhs):
            self.i64ShlRS(sp: sp, r0: &r0, rhs: rhs)
        case .i32ShrSSS(let lhs, let rhs):
            self.i32ShrSSS(sp: sp, r0: &r0, lhs: lhs, rhs: rhs)
        case .i32ShrSSR(let lhs):
            self.i32ShrSSR(sp: sp, r0: &r0, lhs: lhs)
        case .i32ShrSRS(let rhs):
            self.i32ShrSRS(sp: sp, r0: &r0, rhs: rhs)
        case .i64ShrSSS(let lhs, let rhs):
            self.i64ShrSSS(sp: sp, r0: &r0, lhs: lhs, rhs: rhs)
        case .i64ShrSSR(let lhs):
            self.i64ShrSSR(sp: sp, r0: &r0, lhs: lhs)
        case .i64ShrSRS(let rhs):
            self.i64ShrSRS(sp: sp, r0: &r0, rhs: rhs)
        case .i32ShrUSS(let lhs, let rhs):
            self.i32ShrUSS(sp: sp, r0: &r0, lhs: lhs, rhs: rhs)
        case .i32ShrUSR(let lhs):
            self.i32ShrUSR(sp: sp, r0: &r0, lhs: lhs)
        case .i32ShrURS(let rhs):
            self.i32ShrURS(sp: sp, r0: &r0, rhs: rhs)
        case .i64ShrUSS(let lhs, let rhs):
            self.i64ShrUSS(sp: sp, r0: &r0, lhs: lhs, rhs: rhs)
        case .i64ShrUSR(let lhs):
            self.i64ShrUSR(sp: sp, r0: &r0, lhs: lhs)
        case .i64ShrURS(let rhs):
            self.i64ShrURS(sp: sp, r0: &r0, rhs: rhs)
        case .i32RotlSS(let lhs, let rhs):
            self.i32RotlSS(sp: sp, r0: &r0, lhs: lhs, rhs: rhs)
        case .i32RotlSR(let lhs):
            self.i32RotlSR(sp: sp, r0: &r0, lhs: lhs)
        case .i32RotlRS(let rhs):
            self.i32RotlRS(sp: sp, r0: &r0, rhs: rhs)
        case .i64RotlSS(let lhs, let rhs):
            self.i64RotlSS(sp: sp, r0: &r0, lhs: lhs, rhs: rhs)
        case .i64RotlSR(let lhs):
            self.i64RotlSR(sp: sp, r0: &r0, lhs: lhs)
        case .i64RotlRS(let rhs):
            self.i64RotlRS(sp: sp, r0: &r0, rhs: rhs)
        case .i32RotrSS(let lhs, let rhs):
            self.i32RotrSS(sp: sp, r0: &r0, lhs: lhs, rhs: rhs)
        case .i32RotrSR(let lhs):
            self.i32RotrSR(sp: sp, r0: &r0, lhs: lhs)
        case .i32RotrRS(let rhs):
            self.i32RotrRS(sp: sp, r0: &r0, rhs: rhs)
        case .i64RotrSS(let lhs, let rhs):
            self.i64RotrSS(sp: sp, r0: &r0, lhs: lhs, rhs: rhs)
        case .i64RotrSR(let lhs):
            self.i64RotrSR(sp: sp, r0: &r0, lhs: lhs)
        case .i64RotrRS(let rhs):
            self.i64RotrRS(sp: sp, r0: &r0, rhs: rhs)
        case .i32Eq(let binaryOperand):
            self.i32Eq(sp: sp, binaryOperand: binaryOperand)
        case .i64Eq(let binaryOperand):
            self.i64Eq(sp: sp, binaryOperand: binaryOperand)
        case .i32Ne(let binaryOperand):
            self.i32Ne(sp: sp, binaryOperand: binaryOperand)
        case .i64Ne(let binaryOperand):
            self.i64Ne(sp: sp, binaryOperand: binaryOperand)
        case .i32LtS(let binaryOperand):
            self.i32LtS(sp: sp, binaryOperand: binaryOperand)
        case .i64LtS(let binaryOperand):
            self.i64LtS(sp: sp, binaryOperand: binaryOperand)
        case .i32LtU(let binaryOperand):
            self.i32LtU(sp: sp, binaryOperand: binaryOperand)
        case .i64LtU(let binaryOperand):
            self.i64LtU(sp: sp, binaryOperand: binaryOperand)
        case .i32GtS(let binaryOperand):
            self.i32GtS(sp: sp, binaryOperand: binaryOperand)
        case .i64GtS(let binaryOperand):
            self.i64GtS(sp: sp, binaryOperand: binaryOperand)
        case .i32GtU(let binaryOperand):
            self.i32GtU(sp: sp, binaryOperand: binaryOperand)
        case .i64GtU(let binaryOperand):
            self.i64GtU(sp: sp, binaryOperand: binaryOperand)
        case .i32LeS(let binaryOperand):
            self.i32LeS(sp: sp, binaryOperand: binaryOperand)
        case .i64LeS(let binaryOperand):
            self.i64LeS(sp: sp, binaryOperand: binaryOperand)
        case .i32LeU(let binaryOperand):
            self.i32LeU(sp: sp, binaryOperand: binaryOperand)
        case .i64LeU(let binaryOperand):
            self.i64LeU(sp: sp, binaryOperand: binaryOperand)
        case .i32GeS(let binaryOperand):
            self.i32GeS(sp: sp, binaryOperand: binaryOperand)
        case .i64GeS(let binaryOperand):
            self.i64GeS(sp: sp, binaryOperand: binaryOperand)
        case .i32GeU(let binaryOperand):
            self.i32GeU(sp: sp, binaryOperand: binaryOperand)
        case .i64GeU(let binaryOperand):
            self.i64GeU(sp: sp, binaryOperand: binaryOperand)
        case .i32Clz(let unaryOperand):
            self.i32Clz(sp: sp, unaryOperand: unaryOperand)
        case .i64Clz(let unaryOperand):
            self.i64Clz(sp: sp, unaryOperand: unaryOperand)
        case .i32Ctz(let unaryOperand):
            self.i32Ctz(sp: sp, unaryOperand: unaryOperand)
        case .i64Ctz(let unaryOperand):
            self.i64Ctz(sp: sp, unaryOperand: unaryOperand)
        case .i32Popcnt(let unaryOperand):
            self.i32Popcnt(sp: sp, unaryOperand: unaryOperand)
        case .i64Popcnt(let unaryOperand):
            self.i64Popcnt(sp: sp, unaryOperand: unaryOperand)
        case .i32Eqz(let unaryOperand):
            self.i32Eqz(sp: sp, unaryOperand: unaryOperand)
        case .i64Eqz(let unaryOperand):
            self.i64Eqz(sp: sp, unaryOperand: unaryOperand)
        case .f32Add(let binaryOperand):
            self.f32Add(sp: sp, binaryOperand: binaryOperand)
        case .f64Add(let binaryOperand):
            self.f64Add(sp: sp, binaryOperand: binaryOperand)
        case .f32Sub(let binaryOperand):
            self.f32Sub(sp: sp, binaryOperand: binaryOperand)
        case .f64Sub(let binaryOperand):
            self.f64Sub(sp: sp, binaryOperand: binaryOperand)
        case .f32Mul(let binaryOperand):
            self.f32Mul(sp: sp, binaryOperand: binaryOperand)
        case .f64Mul(let binaryOperand):
            self.f64Mul(sp: sp, binaryOperand: binaryOperand)
        case .f32Div(let binaryOperand):
            self.f32Div(sp: sp, binaryOperand: binaryOperand)
        case .f64Div(let binaryOperand):
            self.f64Div(sp: sp, binaryOperand: binaryOperand)
        case .f32Eq(let binaryOperand):
            self.f32Eq(sp: sp, binaryOperand: binaryOperand)
        case .f64Eq(let binaryOperand):
            self.f64Eq(sp: sp, binaryOperand: binaryOperand)
        case .f32Ne(let binaryOperand):
            self.f32Ne(sp: sp, binaryOperand: binaryOperand)
        case .f64Ne(let binaryOperand):
            self.f64Ne(sp: sp, binaryOperand: binaryOperand)
        case .select(let selectOperand):
            try self.select(sp: sp, selectOperand: selectOperand)
        case .refNull(let refNullOperand):
            self.refNull(sp: sp, refNullOperand: refNullOperand)
        case .refIsNull(let refIsNullOperand):
            self.refIsNull(sp: sp, refIsNullOperand: refIsNullOperand)
        case .refFunc(let refFuncOperand):
            self.refFunc(sp: sp, refFuncOperand: refFuncOperand)
        case .tableGet(let tableGetOperand):
            try self.tableGet(sp: sp, tableGetOperand: tableGetOperand)
        case .tableSet(let tableSetOperand):
            try self.tableSet(sp: sp, tableSetOperand: tableSetOperand)
        case .tableSize(let tableSizeOperand):
            self.tableSize(sp: sp, tableSizeOperand: tableSizeOperand)
        case .tableGrow(let tableGrowOperand):
            try self.tableGrow(sp: sp, tableGrowOperand: tableGrowOperand)
        case .tableFill(let tableFillOperand):
            try self.tableFill(sp: sp, tableFillOperand: tableFillOperand)
        case .tableCopy(let tableCopyOperand):
            try self.tableCopy(sp: sp, tableCopyOperand: tableCopyOperand)
        case .tableInit(let tableInitOperand):
            try self.tableInit(sp: sp, tableInitOperand: tableInitOperand)
        case .tableElementDrop(let elementIndex):
            self.tableElementDrop(sp: sp, elementIndex: elementIndex)
        case .onEnter(let onEnterOperand):
            self.onEnter(sp: sp, onEnterOperand: onEnterOperand)
        case .onExit(let onExitOperand):
            self.onExit(sp: sp, onExitOperand: onExitOperand)
        }
        pc += 1
        return true
    }
}

extension Instruction {
    var name: String {
        switch self {
        case .copyStack: return "copyStack"
        case .copyR0ToStackI32: return "copyR0ToStackI32"
        case .copyR0ToStackI64: return "copyR0ToStackI64"
        case .copyR0ToStackF32: return "copyR0ToStackF32"
        case .copyR0ToStackF64: return "copyR0ToStackF64"
        case .globalGet: return "globalGet"
        case .globalSet: return "globalSet"
        case .call: return "call"
        case .compilingCall: return "compilingCall"
        case .internalCall: return "internalCall"
        case .callIndirect: return "callIndirect"
        case .unreachable: return "unreachable"
        case .nop: return "nop"
        case .ifThen: return "ifThen"
        case .br: return "br"
        case .brIf: return "brIf"
        case .brIfNot: return "brIfNot"
        case .brTable: return "brTable"
        case .`return`: return "`return`"
        case .endOfExecution: return "endOfExecution"
        case .i32Load: return "i32Load"
        case .i64Load: return "i64Load"
        case .f32Load: return "f32Load"
        case .f64Load: return "f64Load"
        case .i32Load8S: return "i32Load8S"
        case .i32Load8U: return "i32Load8U"
        case .i32Load16S: return "i32Load16S"
        case .i32Load16U: return "i32Load16U"
        case .i64Load8S: return "i64Load8S"
        case .i64Load8U: return "i64Load8U"
        case .i64Load16S: return "i64Load16S"
        case .i64Load16U: return "i64Load16U"
        case .i64Load32S: return "i64Load32S"
        case .i64Load32U: return "i64Load32U"
        case .i32Store: return "i32Store"
        case .i64Store: return "i64Store"
        case .f32Store: return "f32Store"
        case .f64Store: return "f64Store"
        case .i32Store8: return "i32Store8"
        case .i32Store16: return "i32Store16"
        case .i64Store8: return "i64Store8"
        case .i64Store16: return "i64Store16"
        case .i64Store32: return "i64Store32"
        case .memorySize: return "memorySize"
        case .memoryGrow: return "memoryGrow"
        case .memoryInit: return "memoryInit"
        case .memoryDataDrop: return "memoryDataDrop"
        case .memoryCopy: return "memoryCopy"
        case .memoryFill: return "memoryFill"
        case .numericConst: return "numericConst"
        case .numericFloatUnary: return "numericFloatUnary"
        case .numericIntBinary: return "numericIntBinary"
        case .numericFloatBinary: return "numericFloatBinary"
        case .numericConversion: return "numericConversion"
        case .i32AddSS: return "i32AddSS"
        case .i32AddSR: return "i32AddSR"
        case .i64AddSS: return "i64AddSS"
        case .i64AddSR: return "i64AddSR"
        case .i32MulSS: return "i32MulSS"
        case .i32MulSR: return "i32MulSR"
        case .i64MulSS: return "i64MulSS"
        case .i64MulSR: return "i64MulSR"
        case .i32AndSS: return "i32AndSS"
        case .i32AndSR: return "i32AndSR"
        case .i64AndSS: return "i64AndSS"
        case .i64AndSR: return "i64AndSR"
        case .i32OrSS: return "i32OrSS"
        case .i32OrSR: return "i32OrSR"
        case .i64OrSS: return "i64OrSS"
        case .i64OrSR: return "i64OrSR"
        case .i32XorSS: return "i32XorSS"
        case .i32XorSR: return "i32XorSR"
        case .i64XorSS: return "i64XorSS"
        case .i64XorSR: return "i64XorSR"
        case .i32SubSS: return "i32SubSS"
        case .i32SubSR: return "i32SubSR"
        case .i32SubRS: return "i32SubRS"
        case .i64SubSS: return "i64SubSS"
        case .i64SubSR: return "i64SubSR"
        case .i64SubRS: return "i64SubRS"
        case .i32ShlSS: return "i32ShlSS"
        case .i32ShlSR: return "i32ShlSR"
        case .i32ShlRS: return "i32ShlRS"
        case .i64ShlSS: return "i64ShlSS"
        case .i64ShlSR: return "i64ShlSR"
        case .i64ShlRS: return "i64ShlRS"
        case .i32ShrSSS: return "i32ShrSSS"
        case .i32ShrSSR: return "i32ShrSSR"
        case .i32ShrSRS: return "i32ShrSRS"
        case .i64ShrSSS: return "i64ShrSSS"
        case .i64ShrSSR: return "i64ShrSSR"
        case .i64ShrSRS: return "i64ShrSRS"
        case .i32ShrUSS: return "i32ShrUSS"
        case .i32ShrUSR: return "i32ShrUSR"
        case .i32ShrURS: return "i32ShrURS"
        case .i64ShrUSS: return "i64ShrUSS"
        case .i64ShrUSR: return "i64ShrUSR"
        case .i64ShrURS: return "i64ShrURS"
        case .i32RotlSS: return "i32RotlSS"
        case .i32RotlSR: return "i32RotlSR"
        case .i32RotlRS: return "i32RotlRS"
        case .i64RotlSS: return "i64RotlSS"
        case .i64RotlSR: return "i64RotlSR"
        case .i64RotlRS: return "i64RotlRS"
        case .i32RotrSS: return "i32RotrSS"
        case .i32RotrSR: return "i32RotrSR"
        case .i32RotrRS: return "i32RotrRS"
        case .i64RotrSS: return "i64RotrSS"
        case .i64RotrSR: return "i64RotrSR"
        case .i64RotrRS: return "i64RotrRS"
        case .i32Eq: return "i32Eq"
        case .i64Eq: return "i64Eq"
        case .i32Ne: return "i32Ne"
        case .i64Ne: return "i64Ne"
        case .i32LtS: return "i32LtS"
        case .i64LtS: return "i64LtS"
        case .i32LtU: return "i32LtU"
        case .i64LtU: return "i64LtU"
        case .i32GtS: return "i32GtS"
        case .i64GtS: return "i64GtS"
        case .i32GtU: return "i32GtU"
        case .i64GtU: return "i64GtU"
        case .i32LeS: return "i32LeS"
        case .i64LeS: return "i64LeS"
        case .i32LeU: return "i32LeU"
        case .i64LeU: return "i64LeU"
        case .i32GeS: return "i32GeS"
        case .i64GeS: return "i64GeS"
        case .i32GeU: return "i32GeU"
        case .i64GeU: return "i64GeU"
        case .i32Clz: return "i32Clz"
        case .i64Clz: return "i64Clz"
        case .i32Ctz: return "i32Ctz"
        case .i64Ctz: return "i64Ctz"
        case .i32Popcnt: return "i32Popcnt"
        case .i64Popcnt: return "i64Popcnt"
        case .i32Eqz: return "i32Eqz"
        case .i64Eqz: return "i64Eqz"
        case .f32Add: return "f32Add"
        case .f64Add: return "f64Add"
        case .f32Sub: return "f32Sub"
        case .f64Sub: return "f64Sub"
        case .f32Mul: return "f32Mul"
        case .f64Mul: return "f64Mul"
        case .f32Div: return "f32Div"
        case .f64Div: return "f64Div"
        case .f32Eq: return "f32Eq"
        case .f64Eq: return "f64Eq"
        case .f32Ne: return "f32Ne"
        case .f64Ne: return "f64Ne"
        case .select: return "select"
        case .refNull: return "refNull"
        case .refIsNull: return "refIsNull"
        case .refFunc: return "refFunc"
        case .tableGet: return "tableGet"
        case .tableSet: return "tableSet"
        case .tableSize: return "tableSize"
        case .tableGrow: return "tableGrow"
        case .tableFill: return "tableFill"
        case .tableCopy: return "tableCopy"
        case .tableInit: return "tableInit"
        case .tableElementDrop: return "tableElementDrop"
        case .onEnter: return "onEnter"
        case .onExit: return "onExit"
        }
    }
}


extension ExecutionState {
    mutating func i32AddSS(sp: Sp, r0: inout R0, lhs: VReg, rhs: VReg) { writePReg(&r0, sp[lhs].i32.add(sp[rhs].i32)) }
    mutating func i32AddSR(sp: Sp, r0: inout R0, lhs: VReg) { writePReg(&r0, sp[lhs].i32.add(readPRegI32(r0))) }
    mutating func i64AddSS(sp: Sp, r0: inout R0, lhs: VReg, rhs: VReg) { writePReg(&r0, sp[lhs].i64.add(sp[rhs].i64)) }
    mutating func i64AddSR(sp: Sp, r0: inout R0, lhs: VReg) { writePReg(&r0, sp[lhs].i64.add(readPRegI64(r0))) }
    mutating func i32MulSS(sp: Sp, r0: inout R0, lhs: VReg, rhs: VReg) { writePReg(&r0, sp[lhs].i32.mul(sp[rhs].i32)) }
    mutating func i32MulSR(sp: Sp, r0: inout R0, lhs: VReg) { writePReg(&r0, sp[lhs].i32.mul(readPRegI32(r0))) }
    mutating func i64MulSS(sp: Sp, r0: inout R0, lhs: VReg, rhs: VReg) { writePReg(&r0, sp[lhs].i64.mul(sp[rhs].i64)) }
    mutating func i64MulSR(sp: Sp, r0: inout R0, lhs: VReg) { writePReg(&r0, sp[lhs].i64.mul(readPRegI64(r0))) }
    mutating func i32AndSS(sp: Sp, r0: inout R0, lhs: VReg, rhs: VReg) { writePReg(&r0, sp[lhs].i32.and(sp[rhs].i32)) }
    mutating func i32AndSR(sp: Sp, r0: inout R0, lhs: VReg) { writePReg(&r0, sp[lhs].i32.and(readPRegI32(r0))) }
    mutating func i64AndSS(sp: Sp, r0: inout R0, lhs: VReg, rhs: VReg) { writePReg(&r0, sp[lhs].i64.and(sp[rhs].i64)) }
    mutating func i64AndSR(sp: Sp, r0: inout R0, lhs: VReg) { writePReg(&r0, sp[lhs].i64.and(readPRegI64(r0))) }
    mutating func i32OrSS(sp: Sp, r0: inout R0, lhs: VReg, rhs: VReg) { writePReg(&r0, sp[lhs].i32.or(sp[rhs].i32)) }
    mutating func i32OrSR(sp: Sp, r0: inout R0, lhs: VReg) { writePReg(&r0, sp[lhs].i32.or(readPRegI32(r0))) }
    mutating func i64OrSS(sp: Sp, r0: inout R0, lhs: VReg, rhs: VReg) { writePReg(&r0, sp[lhs].i64.or(sp[rhs].i64)) }
    mutating func i64OrSR(sp: Sp, r0: inout R0, lhs: VReg) { writePReg(&r0, sp[lhs].i64.or(readPRegI64(r0))) }
    mutating func i32XorSS(sp: Sp, r0: inout R0, lhs: VReg, rhs: VReg) { writePReg(&r0, sp[lhs].i32.xor(sp[rhs].i32)) }
    mutating func i32XorSR(sp: Sp, r0: inout R0, lhs: VReg) { writePReg(&r0, sp[lhs].i32.xor(readPRegI32(r0))) }
    mutating func i64XorSS(sp: Sp, r0: inout R0, lhs: VReg, rhs: VReg) { writePReg(&r0, sp[lhs].i64.xor(sp[rhs].i64)) }
    mutating func i64XorSR(sp: Sp, r0: inout R0, lhs: VReg) { writePReg(&r0, sp[lhs].i64.xor(readPRegI64(r0))) }
    mutating func i32SubSS(sp: Sp, r0: inout R0, lhs: VReg, rhs: VReg) { writePReg(&r0, sp[lhs].i32.sub(sp[rhs].i32)) }
    mutating func i32SubSR(sp: Sp, r0: inout R0, lhs: VReg) { writePReg(&r0, sp[lhs].i32.sub(readPRegI32(r0))) }
    mutating func i32SubRS(sp: Sp, r0: inout R0, rhs: VReg) { writePReg(&r0, readPRegI32(r0).sub(sp[rhs].i32)) }
    mutating func i64SubSS(sp: Sp, r0: inout R0, lhs: VReg, rhs: VReg) { writePReg(&r0, sp[lhs].i64.sub(sp[rhs].i64)) }
    mutating func i64SubSR(sp: Sp, r0: inout R0, lhs: VReg) { writePReg(&r0, sp[lhs].i64.sub(readPRegI64(r0))) }
    mutating func i64SubRS(sp: Sp, r0: inout R0, rhs: VReg) { writePReg(&r0, readPRegI64(r0).sub(sp[rhs].i64)) }
    mutating func i32ShlSS(sp: Sp, r0: inout R0, lhs: VReg, rhs: VReg) { writePReg(&r0, sp[lhs].i32.shl(sp[rhs].i32)) }
    mutating func i32ShlSR(sp: Sp, r0: inout R0, lhs: VReg) { writePReg(&r0, sp[lhs].i32.shl(readPRegI32(r0))) }
    mutating func i32ShlRS(sp: Sp, r0: inout R0, rhs: VReg) { writePReg(&r0, readPRegI32(r0).shl(sp[rhs].i32)) }
    mutating func i64ShlSS(sp: Sp, r0: inout R0, lhs: VReg, rhs: VReg) { writePReg(&r0, sp[lhs].i64.shl(sp[rhs].i64)) }
    mutating func i64ShlSR(sp: Sp, r0: inout R0, lhs: VReg) { writePReg(&r0, sp[lhs].i64.shl(readPRegI64(r0))) }
    mutating func i64ShlRS(sp: Sp, r0: inout R0, rhs: VReg) { writePReg(&r0, readPRegI64(r0).shl(sp[rhs].i64)) }
    mutating func i32ShrSSS(sp: Sp, r0: inout R0, lhs: VReg, rhs: VReg) { writePReg(&r0, sp[lhs].i32.shrs(sp[rhs].i32)) }
    mutating func i32ShrSSR(sp: Sp, r0: inout R0, lhs: VReg) { writePReg(&r0, sp[lhs].i32.shrs(readPRegI32(r0))) }
    mutating func i32ShrSRS(sp: Sp, r0: inout R0, rhs: VReg) { writePReg(&r0, readPRegI32(r0).shrs(sp[rhs].i32)) }
    mutating func i64ShrSSS(sp: Sp, r0: inout R0, lhs: VReg, rhs: VReg) { writePReg(&r0, sp[lhs].i64.shrs(sp[rhs].i64)) }
    mutating func i64ShrSSR(sp: Sp, r0: inout R0, lhs: VReg) { writePReg(&r0, sp[lhs].i64.shrs(readPRegI64(r0))) }
    mutating func i64ShrSRS(sp: Sp, r0: inout R0, rhs: VReg) { writePReg(&r0, readPRegI64(r0).shrs(sp[rhs].i64)) }
    mutating func i32ShrUSS(sp: Sp, r0: inout R0, lhs: VReg, rhs: VReg) { writePReg(&r0, sp[lhs].i32.shru(sp[rhs].i32)) }
    mutating func i32ShrUSR(sp: Sp, r0: inout R0, lhs: VReg) { writePReg(&r0, sp[lhs].i32.shru(readPRegI32(r0))) }
    mutating func i32ShrURS(sp: Sp, r0: inout R0, rhs: VReg) { writePReg(&r0, readPRegI32(r0).shru(sp[rhs].i32)) }
    mutating func i64ShrUSS(sp: Sp, r0: inout R0, lhs: VReg, rhs: VReg) { writePReg(&r0, sp[lhs].i64.shru(sp[rhs].i64)) }
    mutating func i64ShrUSR(sp: Sp, r0: inout R0, lhs: VReg) { writePReg(&r0, sp[lhs].i64.shru(readPRegI64(r0))) }
    mutating func i64ShrURS(sp: Sp, r0: inout R0, rhs: VReg) { writePReg(&r0, readPRegI64(r0).shru(sp[rhs].i64)) }
    mutating func i32RotlSS(sp: Sp, r0: inout R0, lhs: VReg, rhs: VReg) { writePReg(&r0, sp[lhs].i32.rotl(sp[rhs].i32)) }
    mutating func i32RotlSR(sp: Sp, r0: inout R0, lhs: VReg) { writePReg(&r0, sp[lhs].i32.rotl(readPRegI32(r0))) }
    mutating func i32RotlRS(sp: Sp, r0: inout R0, rhs: VReg) { writePReg(&r0, readPRegI32(r0).rotl(sp[rhs].i32)) }
    mutating func i64RotlSS(sp: Sp, r0: inout R0, lhs: VReg, rhs: VReg) { writePReg(&r0, sp[lhs].i64.rotl(sp[rhs].i64)) }
    mutating func i64RotlSR(sp: Sp, r0: inout R0, lhs: VReg) { writePReg(&r0, sp[lhs].i64.rotl(readPRegI64(r0))) }
    mutating func i64RotlRS(sp: Sp, r0: inout R0, rhs: VReg) { writePReg(&r0, readPRegI64(r0).rotl(sp[rhs].i64)) }
    mutating func i32RotrSS(sp: Sp, r0: inout R0, lhs: VReg, rhs: VReg) { writePReg(&r0, sp[lhs].i32.rotr(sp[rhs].i32)) }
    mutating func i32RotrSR(sp: Sp, r0: inout R0, lhs: VReg) { writePReg(&r0, sp[lhs].i32.rotr(readPRegI32(r0))) }
    mutating func i32RotrRS(sp: Sp, r0: inout R0, rhs: VReg) { writePReg(&r0, readPRegI32(r0).rotr(sp[rhs].i32)) }
    mutating func i64RotrSS(sp: Sp, r0: inout R0, lhs: VReg, rhs: VReg) { writePReg(&r0, sp[lhs].i64.rotr(sp[rhs].i64)) }
    mutating func i64RotrSR(sp: Sp, r0: inout R0, lhs: VReg) { writePReg(&r0, sp[lhs].i64.rotr(readPRegI64(r0))) }
    mutating func i64RotrRS(sp: Sp, r0: inout R0, rhs: VReg) { writePReg(&r0, readPRegI64(r0).rotr(sp[rhs].i64)) }
    mutating func i32Eq(sp: Sp, binaryOperand: Instruction.BinaryOperand) {
        sp[binaryOperand.result] = sp[binaryOperand.lhs].i32.eq(sp[binaryOperand.rhs].i32).untyped
    }
    mutating func i64Eq(sp: Sp, binaryOperand: Instruction.BinaryOperand) {
        sp[binaryOperand.result] = sp[binaryOperand.lhs].i64.eq(sp[binaryOperand.rhs].i64).untyped
    }
    mutating func i32Ne(sp: Sp, binaryOperand: Instruction.BinaryOperand) {
        sp[binaryOperand.result] = sp[binaryOperand.lhs].i32.ne(sp[binaryOperand.rhs].i32).untyped
    }
    mutating func i64Ne(sp: Sp, binaryOperand: Instruction.BinaryOperand) {
        sp[binaryOperand.result] = sp[binaryOperand.lhs].i64.ne(sp[binaryOperand.rhs].i64).untyped
    }
    mutating func i32LtS(sp: Sp, binaryOperand: Instruction.BinaryOperand) {
        sp[binaryOperand.result] = sp[binaryOperand.lhs].i32.lts(sp[binaryOperand.rhs].i32).untyped
    }
    mutating func i64LtS(sp: Sp, binaryOperand: Instruction.BinaryOperand) {
        sp[binaryOperand.result] = sp[binaryOperand.lhs].i64.lts(sp[binaryOperand.rhs].i64).untyped
    }
    mutating func i32LtU(sp: Sp, binaryOperand: Instruction.BinaryOperand) {
        sp[binaryOperand.result] = sp[binaryOperand.lhs].i32.ltu(sp[binaryOperand.rhs].i32).untyped
    }
    mutating func i64LtU(sp: Sp, binaryOperand: Instruction.BinaryOperand) {
        sp[binaryOperand.result] = sp[binaryOperand.lhs].i64.ltu(sp[binaryOperand.rhs].i64).untyped
    }
    mutating func i32GtS(sp: Sp, binaryOperand: Instruction.BinaryOperand) {
        sp[binaryOperand.result] = sp[binaryOperand.lhs].i32.gts(sp[binaryOperand.rhs].i32).untyped
    }
    mutating func i64GtS(sp: Sp, binaryOperand: Instruction.BinaryOperand) {
        sp[binaryOperand.result] = sp[binaryOperand.lhs].i64.gts(sp[binaryOperand.rhs].i64).untyped
    }
    mutating func i32GtU(sp: Sp, binaryOperand: Instruction.BinaryOperand) {
        sp[binaryOperand.result] = sp[binaryOperand.lhs].i32.gtu(sp[binaryOperand.rhs].i32).untyped
    }
    mutating func i64GtU(sp: Sp, binaryOperand: Instruction.BinaryOperand) {
        sp[binaryOperand.result] = sp[binaryOperand.lhs].i64.gtu(sp[binaryOperand.rhs].i64).untyped
    }
    mutating func i32LeS(sp: Sp, binaryOperand: Instruction.BinaryOperand) {
        sp[binaryOperand.result] = sp[binaryOperand.lhs].i32.les(sp[binaryOperand.rhs].i32).untyped
    }
    mutating func i64LeS(sp: Sp, binaryOperand: Instruction.BinaryOperand) {
        sp[binaryOperand.result] = sp[binaryOperand.lhs].i64.les(sp[binaryOperand.rhs].i64).untyped
    }
    mutating func i32LeU(sp: Sp, binaryOperand: Instruction.BinaryOperand) {
        sp[binaryOperand.result] = sp[binaryOperand.lhs].i32.leu(sp[binaryOperand.rhs].i32).untyped
    }
    mutating func i64LeU(sp: Sp, binaryOperand: Instruction.BinaryOperand) {
        sp[binaryOperand.result] = sp[binaryOperand.lhs].i64.leu(sp[binaryOperand.rhs].i64).untyped
    }
    mutating func i32GeS(sp: Sp, binaryOperand: Instruction.BinaryOperand) {
        sp[binaryOperand.result] = sp[binaryOperand.lhs].i32.ges(sp[binaryOperand.rhs].i32).untyped
    }
    mutating func i64GeS(sp: Sp, binaryOperand: Instruction.BinaryOperand) {
        sp[binaryOperand.result] = sp[binaryOperand.lhs].i64.ges(sp[binaryOperand.rhs].i64).untyped
    }
    mutating func i32GeU(sp: Sp, binaryOperand: Instruction.BinaryOperand) {
        sp[binaryOperand.result] = sp[binaryOperand.lhs].i32.geu(sp[binaryOperand.rhs].i32).untyped
    }
    mutating func i64GeU(sp: Sp, binaryOperand: Instruction.BinaryOperand) {
        sp[binaryOperand.result] = sp[binaryOperand.lhs].i64.geu(sp[binaryOperand.rhs].i64).untyped
    }
    mutating func f32Add(sp: Sp, binaryOperand: Instruction.BinaryOperand) {
        sp[binaryOperand.result] = sp[binaryOperand.lhs].f32.add(sp[binaryOperand.rhs].f32).untyped
    }
    mutating func f64Add(sp: Sp, binaryOperand: Instruction.BinaryOperand) {
        sp[binaryOperand.result] = sp[binaryOperand.lhs].f64.add(sp[binaryOperand.rhs].f64).untyped
    }
    mutating func f32Sub(sp: Sp, binaryOperand: Instruction.BinaryOperand) {
        sp[binaryOperand.result] = sp[binaryOperand.lhs].f32.sub(sp[binaryOperand.rhs].f32).untyped
    }
    mutating func f64Sub(sp: Sp, binaryOperand: Instruction.BinaryOperand) {
        sp[binaryOperand.result] = sp[binaryOperand.lhs].f64.sub(sp[binaryOperand.rhs].f64).untyped
    }
    mutating func f32Mul(sp: Sp, binaryOperand: Instruction.BinaryOperand) {
        sp[binaryOperand.result] = sp[binaryOperand.lhs].f32.mul(sp[binaryOperand.rhs].f32).untyped
    }
    mutating func f64Mul(sp: Sp, binaryOperand: Instruction.BinaryOperand) {
        sp[binaryOperand.result] = sp[binaryOperand.lhs].f64.mul(sp[binaryOperand.rhs].f64).untyped
    }
    mutating func f32Div(sp: Sp, binaryOperand: Instruction.BinaryOperand) {
        sp[binaryOperand.result] = sp[binaryOperand.lhs].f32.div(sp[binaryOperand.rhs].f32).untyped
    }
    mutating func f64Div(sp: Sp, binaryOperand: Instruction.BinaryOperand) {
        sp[binaryOperand.result] = sp[binaryOperand.lhs].f64.div(sp[binaryOperand.rhs].f64).untyped
    }
    mutating func f32Eq(sp: Sp, binaryOperand: Instruction.BinaryOperand) {
        sp[binaryOperand.result] = sp[binaryOperand.lhs].f32.eq(sp[binaryOperand.rhs].f32).untyped
    }
    mutating func f64Eq(sp: Sp, binaryOperand: Instruction.BinaryOperand) {
        sp[binaryOperand.result] = sp[binaryOperand.lhs].f64.eq(sp[binaryOperand.rhs].f64).untyped
    }
    mutating func f32Ne(sp: Sp, binaryOperand: Instruction.BinaryOperand) {
        sp[binaryOperand.result] = sp[binaryOperand.lhs].f32.ne(sp[binaryOperand.rhs].f32).untyped
    }
    mutating func f64Ne(sp: Sp, binaryOperand: Instruction.BinaryOperand) {
        sp[binaryOperand.result] = sp[binaryOperand.lhs].f64.ne(sp[binaryOperand.rhs].f64).untyped
    }
    mutating func i32Clz(sp: Sp, unaryOperand: Instruction.UnaryOperand) {
        sp[unaryOperand.result] = sp[unaryOperand.input].i32.clz.untyped
    }
    mutating func i64Clz(sp: Sp, unaryOperand: Instruction.UnaryOperand) {
        sp[unaryOperand.result] = sp[unaryOperand.input].i64.clz.untyped
    }
    mutating func i32Ctz(sp: Sp, unaryOperand: Instruction.UnaryOperand) {
        sp[unaryOperand.result] = sp[unaryOperand.input].i32.ctz.untyped
    }
    mutating func i64Ctz(sp: Sp, unaryOperand: Instruction.UnaryOperand) {
        sp[unaryOperand.result] = sp[unaryOperand.input].i64.ctz.untyped
    }
    mutating func i32Popcnt(sp: Sp, unaryOperand: Instruction.UnaryOperand) {
        sp[unaryOperand.result] = sp[unaryOperand.input].i32.popcnt.untyped
    }
    mutating func i64Popcnt(sp: Sp, unaryOperand: Instruction.UnaryOperand) {
        sp[unaryOperand.result] = sp[unaryOperand.input].i64.popcnt.untyped
    }
    mutating func i32Eqz(sp: Sp, unaryOperand: Instruction.UnaryOperand) {
        sp[unaryOperand.result] = sp[unaryOperand.input].i32.eqz.untyped
    }
    mutating func i64Eqz(sp: Sp, unaryOperand: Instruction.UnaryOperand) {
        sp[unaryOperand.result] = sp[unaryOperand.input].i64.eqz.untyped
    }
    mutating func i32Load(sp: Sp, md: Md, ms: Ms, loadOperand: Instruction.LoadOperand) throws {
        try memoryLoad(sp: sp, md: md, ms: ms, loadOperand: loadOperand, loadAs: UInt32.self, castToValue: { .i32($0) })
    }
    mutating func i64Load(sp: Sp, md: Md, ms: Ms, loadOperand: Instruction.LoadOperand) throws {
        try memoryLoad(sp: sp, md: md, ms: ms, loadOperand: loadOperand, loadAs: UInt64.self, castToValue: { .i64($0) })
    }
    mutating func f32Load(sp: Sp, md: Md, ms: Ms, loadOperand: Instruction.LoadOperand) throws {
        try memoryLoad(sp: sp, md: md, ms: ms, loadOperand: loadOperand, loadAs: UInt32.self, castToValue: { .rawF32($0) })
    }
    mutating func f64Load(sp: Sp, md: Md, ms: Ms, loadOperand: Instruction.LoadOperand) throws {
        try memoryLoad(sp: sp, md: md, ms: ms, loadOperand: loadOperand, loadAs: UInt64.self, castToValue: { .rawF64($0) })
    }
    mutating func i32Load8S(sp: Sp, md: Md, ms: Ms, loadOperand: Instruction.LoadOperand) throws {
        try memoryLoad(sp: sp, md: md, ms: ms, loadOperand: loadOperand, loadAs: Int8.self, castToValue: { .init(signed: Int32($0)) })
    }
    mutating func i32Load8U(sp: Sp, md: Md, ms: Ms, loadOperand: Instruction.LoadOperand) throws {
        try memoryLoad(sp: sp, md: md, ms: ms, loadOperand: loadOperand, loadAs: UInt8.self, castToValue: { .i32(UInt32($0)) })
    }
    mutating func i32Load16S(sp: Sp, md: Md, ms: Ms, loadOperand: Instruction.LoadOperand) throws {
        try memoryLoad(sp: sp, md: md, ms: ms, loadOperand: loadOperand, loadAs: Int16.self, castToValue: { .init(signed: Int32($0)) })
    }
    mutating func i32Load16U(sp: Sp, md: Md, ms: Ms, loadOperand: Instruction.LoadOperand) throws {
        try memoryLoad(sp: sp, md: md, ms: ms, loadOperand: loadOperand, loadAs: UInt16.self, castToValue: { .i32(UInt32($0)) })
    }
    mutating func i64Load8S(sp: Sp, md: Md, ms: Ms, loadOperand: Instruction.LoadOperand) throws {
        try memoryLoad(sp: sp, md: md, ms: ms, loadOperand: loadOperand, loadAs: Int8.self, castToValue: { .init(signed: Int64($0)) })
    }
    mutating func i64Load8U(sp: Sp, md: Md, ms: Ms, loadOperand: Instruction.LoadOperand) throws {
        try memoryLoad(sp: sp, md: md, ms: ms, loadOperand: loadOperand, loadAs: UInt8.self, castToValue: { .i64(UInt64($0)) })
    }
    mutating func i64Load16S(sp: Sp, md: Md, ms: Ms, loadOperand: Instruction.LoadOperand) throws {
        try memoryLoad(sp: sp, md: md, ms: ms, loadOperand: loadOperand, loadAs: Int16.self, castToValue: { .init(signed: Int64($0)) })
    }
    mutating func i64Load16U(sp: Sp, md: Md, ms: Ms, loadOperand: Instruction.LoadOperand) throws {
        try memoryLoad(sp: sp, md: md, ms: ms, loadOperand: loadOperand, loadAs: UInt16.self, castToValue: { .i64(UInt64($0)) })
    }
    mutating func i64Load32S(sp: Sp, md: Md, ms: Ms, loadOperand: Instruction.LoadOperand) throws {
        try memoryLoad(sp: sp, md: md, ms: ms, loadOperand: loadOperand, loadAs: Int32.self, castToValue: { .init(signed: Int64($0)) })
    }
    mutating func i64Load32U(sp: Sp, md: Md, ms: Ms, loadOperand: Instruction.LoadOperand) throws {
        try memoryLoad(sp: sp, md: md, ms: ms, loadOperand: loadOperand, loadAs: UInt32.self, castToValue: { .i64(UInt64($0)) })
    }
    mutating func i32Store(sp: Sp, md: Md, ms: Ms, storeOperand: Instruction.StoreOperand) throws {
        try memoryStore(sp: sp, md: md, ms: ms, storeOperand: storeOperand, castFromValue: { $0.i32 })
    }
    mutating func i64Store(sp: Sp, md: Md, ms: Ms, storeOperand: Instruction.StoreOperand) throws {
        try memoryStore(sp: sp, md: md, ms: ms, storeOperand: storeOperand, castFromValue: { $0.i64 })
    }
    mutating func f32Store(sp: Sp, md: Md, ms: Ms, storeOperand: Instruction.StoreOperand) throws {
        try memoryStore(sp: sp, md: md, ms: ms, storeOperand: storeOperand, castFromValue: { $0.rawF32 })
    }
    mutating func f64Store(sp: Sp, md: Md, ms: Ms, storeOperand: Instruction.StoreOperand) throws {
        try memoryStore(sp: sp, md: md, ms: ms, storeOperand: storeOperand, castFromValue: { $0.rawF64 })
    }
    mutating func i32Store8(sp: Sp, md: Md, ms: Ms, storeOperand: Instruction.StoreOperand) throws {
        try memoryStore(sp: sp, md: md, ms: ms, storeOperand: storeOperand, castFromValue: { UInt8(truncatingIfNeeded: $0.i32) })
    }
    mutating func i32Store16(sp: Sp, md: Md, ms: Ms, storeOperand: Instruction.StoreOperand) throws {
        try memoryStore(sp: sp, md: md, ms: ms, storeOperand: storeOperand, castFromValue: { UInt16(truncatingIfNeeded: $0.i32) })
    }
    mutating func i64Store8(sp: Sp, md: Md, ms: Ms, storeOperand: Instruction.StoreOperand) throws {
        try memoryStore(sp: sp, md: md, ms: ms, storeOperand: storeOperand, castFromValue: { UInt8(truncatingIfNeeded: $0.i64) })
    }
    mutating func i64Store16(sp: Sp, md: Md, ms: Ms, storeOperand: Instruction.StoreOperand) throws {
        try memoryStore(sp: sp, md: md, ms: ms, storeOperand: storeOperand, castFromValue: { UInt16(truncatingIfNeeded: $0.i64) })
    }
    mutating func i64Store32(sp: Sp, md: Md, ms: Ms, storeOperand: Instruction.StoreOperand) throws {
        try memoryStore(sp: sp, md: md, ms: ms, storeOperand: storeOperand, castFromValue: { UInt32(truncatingIfNeeded: $0.i64) })
    }
}
