;; An exnref stays valid after the call that caught the exception returns:
;; it can be stored in a table or a global and rethrown by a later call.
(module
  (tag $t (param i32))
  (table $exns 2 exnref)
  (global $saved (mut exnref) (ref.null exn))

  ;; Throws `value`, catches it with catch_ref and stores the exnref.
  (func $catch (param $value i32) (result exnref)
    (local $exn exnref)
    (block $caught (result i32 exnref)
      (try_table (catch_ref $t $caught) (throw $t (local.get $value)))
      (unreachable)
    )
    (local.set $exn)
    (drop)
    (local.get $exn)
  )
  (func (export "store-in-table") (param $index i32) (param $value i32)
    (table.set $exns (local.get $index) (call $catch (local.get $value)))
  )
  (func (export "store-in-global") (param $value i32)
    (global.set $saved (call $catch (local.get $value)))
  )
  ;; Catches everything with catch_all_ref and stores the exnref.
  (func (export "store-any-in-global") (param $value i32)
    (block $caught (result exnref)
      (try_table (catch_all_ref $caught) (throw $t (local.get $value)))
      (unreachable)
    )
    (global.set $saved)
  )

  ;; Rethrows a stored exnref and returns the payload.
  (func $payload (param exnref) (result i32)
    (block $caught (result i32)
      (try_table (catch $t $caught) (throw_ref (local.get 0)))
      (unreachable)
    )
  )
  (func (export "rethrow-from-table") (param $index i32) (result i32)
    (call $payload (table.get $exns (local.get $index)))
  )
  (func (export "rethrow-from-global") (result i32)
    (call $payload (global.get $saved))
  )
)

(invoke "store-in-table" (i32.const 0) (i32.const 10))
(invoke "store-in-table" (i32.const 1) (i32.const 20))
(invoke "store-in-global" (i32.const 30))
(assert_return (invoke "rethrow-from-table" (i32.const 0)) (i32.const 10))
(assert_return (invoke "rethrow-from-table" (i32.const 1)) (i32.const 20))
(assert_return (invoke "rethrow-from-global") (i32.const 30))
(invoke "store-any-in-global" (i32.const 40))
(assert_return (invoke "rethrow-from-global") (i32.const 40))
(assert_return (invoke "rethrow-from-table" (i32.const 0)) (i32.const 10))
